/**
 * sync-version.js
 *
 * Reads the "version" field from package.json and writes it into
 * src/version.ts so the compiled exe always reports the correct version.
 *
 * Run automatically by the build:exe script (see package.json).
 */

const fs = require("fs");
const path = require("path");

const rootDir = path.join(__dirname, "..");
const pkg = JSON.parse(fs.readFileSync(path.join(rootDir, "package.json"), "utf8"));
const version = pkg.version;

const versionFile = path.join(rootDir, "src", "version.ts");
const content = `/**
 * Application version — auto-generated by scripts/sync-version.js.
 * Do NOT edit this file manually. Bump the version in package.json instead.
 */
export const APP_VERSION = "${version}";
`;

fs.writeFileSync(versionFile, content, "utf8");
console.log(`✓ Synced version ${version} → src/version.ts`);
